### ISSUE TITLE
Fox notice in script

### ISSUE THREAD

**Issue by amitaibu** [shoov/php-ci#4]
![viewing_a_message___shoov](https://cloud.githubusercontent.com/assets/125707/8397440/f4276984-1dd3-11e5-8e40-d75f7c8f1c1d.jpg)

**Comment by amitaibu** [comment]
@solker ^^

**Comment by solker** [comment]
@amitaibu 
Only one place in the code where we are using forEach -> https://github.com/shoov/php-ci/blob/master/export-vars.js#L39

Looking like env not set. How I understand env should be filled because contain tokens to auth in shoov. Question is how this .shoov.yml is come to php-ci? There is place where are we check for .shoov.yml correct?

**Comment by amitaibu** [comment]
Already solved.
